services: 

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: nodeflow-backend
    env_file:
      - ${ENV_FILE:-.env}
    ports:
      - '8001:8001'
    environment:
      SOLENOID_TESTER_URL: http://solenoid-tester:8002
      SENSOR_TESTER_URL: http://sensor-tester:8003
    depends_on:
      - postgresql
      - sensor-tester
    volumes: 
      - './backend:/app'
    
  frontend: 
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile
    image: nodeflow-frontend
    env_file: 
      - ${ENV_FILE:-.env}
    ports:
      - '3001:81'
    depends_on: 
      - backend
    tty: true
    volumes: 
      - './frontend/src:/app/src'

  postgresql:
    image: postgres:16
    environment:
      POSTGRES_DB: nodeflow
      POSTGRES_USER: nodeflow
      POSTGRES_PASSWORD: nf_password  
    ports:
      - '5433:5432'
    volumes: 
      - postgresql-16-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    ports:
      - '8889:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  solenoid-tester:
    build:
      context: ./TestSolenoid
      dockerfile: Dockerfile
    image: nodeflow-soldenoid-tester
    container_name: TestSolenoid
    environment:
      INITIAL_SOLENOID_STATE: closed
    ports:
      - '127.0.0.1:8002:8002'
    healthcheck:
      test: [
        'CMD',
        'python',
        '-c',
        "import urllib.request; urllib.request.urlopen('http://localhost:8002/health')"
      ]
      interval: 10s
      timeout: 3s
      retries: 3

  sensor-tester:
    build:
      context: ./TestSensor
      dockerfile: Dockerfile
    container_name: TestSensor
    environment:
      INITIAL_SENSOR_VALUE: 0.40
      INITIAL_SENSOR_MODE: sine
      SENSOR_TYPE: soil_moisture
      SENSOR_MEASUREMENT: vwc
    ports:
      - "127.0.0.1:8003:8003"
    healthcheck:
      test: [
        "CMD",
        "python",
        "-c",
        "import urllib.request; urllib.request.urlopen('http://localhost:8003/health')"
      ]
      interval: 10s
      timeout: 3s
      retries: 3
    
volumes:
  postgresql-16-data:
  pgadmin-data:
