"""baseline current NodeFlow schema

Revision ID: c730fbb898c4
Revises: 
Create Date: 2026-08-12 22:21:32.955428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c730fbb898c4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activation_prefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('measurement', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('condition_operator', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('condition_value', sa.Float(), nullable=False),
    sa.Column('close_condition_operator', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('close_condition_value', sa.Float(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activation_prefs_group_id'), 'activation_prefs', ['group_id'], unique=False)
    op.create_index(op.f('ix_activation_prefs_user_id'), 'activation_prefs', ['user_id'], unique=False)
    op.create_index(op.f('ix_activation_prefs_uuid'), 'activation_prefs', ['uuid'], unique=False)
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('irrigation_mode', sqlmodel.sql.sqltypes.AutoString(), server_default='auto', nullable=False),
    sa.CheckConstraint("irrigation_mode IN ('manual', 'auto')", name='valid_irrigation_mode'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_uuid'), 'groups', ['uuid'], unique=False)
    op.create_table('logger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('logger_id', sa.Integer(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('update_interval', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logger_user_id'), 'logger', ['user_id'], unique=False)
    op.create_index(op.f('ix_logger_uuid'), 'logger', ['uuid'], unique=False)
    op.create_table('notification_prefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('condition', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notification_frequency_seconds', sa.Float(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_prefs_user_id'), 'notification_prefs', ['user_id'], unique=False)
    op.create_table('sensor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('legacy_cell_id', sa.Integer(), nullable=True),
    sa.Column('sensor_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('logger_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_legacy_cell_id'), 'sensor', ['legacy_cell_id'], unique=False)
    op.create_index(op.f('ix_sensor_user_id'), 'sensor', ['user_id'], unique=False)
    op.create_index(op.f('ix_sensor_uuid'), 'sensor', ['uuid'], unique=False)
    op.create_table('sensor_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_uuid', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('measurement', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_readings_measurement'), 'sensor_readings', ['measurement'], unique=False)
    op.create_index(op.f('ix_sensor_readings_sensor_uuid'), 'sensor_readings', ['sensor_uuid'], unique=False)
    op.create_index(op.f('ix_sensor_readings_timestamp'), 'sensor_readings', ['timestamp'], unique=False)
    op.create_index(op.f('ix_sensor_readings_user_id'), 'sensor_readings', ['user_id'], unique=False)
    op.create_table('solenoid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active_state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('logger_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solenoid_user_id'), 'solenoid', ['user_id'], unique=False)
    op.create_index(op.f('ix_solenoid_uuid'), 'solenoid', ['uuid'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_api_key'), 'users', ['api_key'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('oauth_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('access_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('refresh_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_tokens_refresh_token'), 'oauth_tokens', ['refresh_token'], unique=False)
    op.create_index(op.f('ix_oauth_tokens_user_id'), 'oauth_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oauth_tokens_user_id'), table_name='oauth_tokens')
    op.drop_index(op.f('ix_oauth_tokens_refresh_token'), table_name='oauth_tokens')
    op.drop_table('oauth_tokens')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_api_key'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_solenoid_uuid'), table_name='solenoid')
    op.drop_index(op.f('ix_solenoid_user_id'), table_name='solenoid')
    op.drop_table('solenoid')
    op.drop_index(op.f('ix_sensor_readings_user_id'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_timestamp'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_sensor_uuid'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_measurement'), table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_index(op.f('ix_sensor_uuid'), table_name='sensor')
    op.drop_index(op.f('ix_sensor_user_id'), table_name='sensor')
    op.drop_index(op.f('ix_sensor_legacy_cell_id'), table_name='sensor')
    op.drop_table('sensor')
    op.drop_index(op.f('ix_notification_prefs_user_id'), table_name='notification_prefs')
    op.drop_table('notification_prefs')
    op.drop_index(op.f('ix_logger_uuid'), table_name='logger')
    op.drop_index(op.f('ix_logger_user_id'), table_name='logger')
    op.drop_table('logger')
    op.drop_index(op.f('ix_groups_uuid'), table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_activation_prefs_uuid'), table_name='activation_prefs')
    op.drop_index(op.f('ix_activation_prefs_user_id'), table_name='activation_prefs')
    op.drop_index(op.f('ix_activation_prefs_group_id'), table_name='activation_prefs')
    op.drop_table('activation_prefs')
    # ### end Alembic commands ###
