"""enforce globally unique logger ids

Revision ID: d5a3bf84003b
Revises: e926acd0269b
Create Date: 2026-08-17 21:34:38.580305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5a3bf84003b'
down_revision: Union[str, Sequence[str], None] = 'e926acd0269b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_logger_logger_id', 'logger', ['logger_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_logger_logger_id', 'logger', type_='unique')
    # ### end Alembic commands ###
