"""prevent duplicate legacy sensor mappings

Revision ID: e926acd0269b
Revises: f772fae46280
Create Date: 2026-08-17 21:13:04.266525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e926acd0269b'
down_revision: Union[str, Sequence[str], None] = 'f772fae46280'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_sensor_user_logger_legacy_type', 'sensor', ['user_id', 'logger_id', 'legacy_cell_id', 'sensor_type'], unique=True, postgresql_where=sa.text('legacy_cell_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_sensor_user_logger_legacy_type', table_name='sensor', postgresql_where=sa.text('legacy_cell_id IS NOT NULL'))
    # ### end Alembic commands ###
