"""allow nullable sensor ids and add lookup indexes

Revision ID: f772fae46280
Revises: c730fbb898c4
Create Date: 2026-08-17 21:00:59.462624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f772fae46280'
down_revision: Union[str, Sequence[str], None] = 'c730fbb898c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sensor', 'sensor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_sensor_sensor_id'), 'sensor', ['sensor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensor_sensor_id'), table_name='sensor')
    op.alter_column('sensor', 'sensor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
