---
name: Deploy

permissions:
  contents: read
  issues: write
  pull-requests: write

on:
  push:
  workflow_dispatch:

concurrency:
  group: production
  cancel-in-progress: true

jobs:
  deploy:

    runs-on: ubuntu-latest
    environment:
      name: development
      url: http://${{ vars.PROD_HOST }}:3001/

    steps:
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PROD_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ vars.PROD_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh ${{ secrets.PROD_USER }}@${{ vars.PROD_HOST }} << 'EOF'
            set -e

            export COMPOSE_PROGRESS=plain
            export NO_COLOR=1

            export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
            export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
            export AWS_DEFAULT_REGION=us-west-2

            APP_DIR="NodeFlow"
            REPO_URL="https://github.com/jlab-sensing/NodeFlow.git"

            echo "::group::Cloning repository"
            sudo rm -rf $APP_DIR
            git clone "$REPO_URL" "$APP_DIR"
            cd "$APP_DIR"
            git fetch origin
            git reset --hard ${{ steps.pr.outputs.sha }}
            echo "::endgroup::"

            echo "::group::Setting up env file"
            aws s3 cp s3://nodeflow-ucsc/secrets .env
            sed -i "s/localhost/${{ vars.PROD_HOST }}/g" .env
            echo "::endgroup::"

            echo "::group::Remove previous deployment"
            docker ps -aq | xargs -r docker stop
            docker ps -aq | xargs -r docker rm
            docker system prune -af --volumes
            docker volume prune -a -f
            echo "::endgroup::"

            echo "::group::Starting services"
            docker compose pull --ignore-buildable
            docker compose up -d --build
            sleep 5
            echo "::endgroup::"

            echo "::group::Waiting for startup"
            sleep 15
            echo "::endgroup::"

            echo "::group::Startup logs"
            docker compose logs --no-color
            echo "::endgroup::"
          EOF

